class objectContainer:
    def __init__(self):
        self.FP = [None] * 24
        self.PF = [[0 for _ in range(26)] for _ in range(67)]
        self.T = [0] * (9 + 1)
        self.SX = [0] * 1001
        self.SY = [0] * 1001
        self.MX = [0] * 1001
        self.MY = [0] * 1001
        self.FX = [0] * 1001
        self.FY = [0] * 1001
        self.BX = [0] * 1301
        self.BY = [0] * 1301

        self.XBot = 2
        self.YBot = 2
        self.XTop = 65
        self.YTop = 24
        self.TMax = 9
        self.YSize = 23
        self.XSize = 64
        self.SNum = 0
        self.MNum = 0
        self.FNum = 0
        self.BNum = 0
        self.GenNum = 0
        self.PX = 0
        self.PY = 0
        self.Difficulty = 2

        self.HideOpenWall = False
        self.GravOn = False
        self.Sideways = False
        self.HideGems = False
        self.HideStairs = False
        self.HideCreate = True
        self.MagicEWalls = True
        self.FloorPattern = False
        self.HideLevel = False
        self.FastPC = True
        self.MixUp = False
        GemColor = 0;
        HideTrap = False;

        self.Slow = None
        self.Medium = None
        self.Fast = None

        self.Null = 0
        self.Block = chr(178)
        self.Whip = chr(244)
        self.Stairs = chr(240)
        self.Chest = chr(67)
        self.SlowTime = chr(232)
        self.Gem = chr(4)
        self.Invisible = chr(173)
        self.Teleport = chr(24)
        self.Key = chr(140)
        self.Door = chr(236)
        self.Wall = chr(219)
        self.SpeedTime = chr(233)
        self.Trap = chr(249)
        self.River = chr(247)
        self.Power = chr(9)
        self.Forest = chr(219)
        self.Tree = chr(5)
        self.Bomb = chr(157)
        self.Lava = chr(178)
        self.Pit = chr(176)
        self.Tome = chr(12)
        self.Tunnel = chr(239)
        self.Freeze = chr(159)
        self.Nugget = chr(15)
        self.Quake = chr(0)
        self.IBlock = chr(30)
        self.IWall = chr(0)
        self.IDoor = chr(0)
        self.Stop = chr(0)
        self.Trap2 = chr(0)
        self.Zap = chr(30)
        self.Create = chr(31)
        self.Generator = chr(6)
        self.Trap3 = chr(0)
        self.MBlock = chr(178)
        self.Trap4 = chr(0)
        self.Player = chr(2)
        self.Show_Gems = chr(0)
        self.Tablet = chr(254)
        self.ZBlock = chr(178)
        self.BlockSpell = chr(0)
        self.Chance = chr(63)
        self.Statue = chr(1)
        self.WallVanish = chr(0)
        self.K = chr(0)
        self.R = chr(0)
        self.O = chr(0)
        self.Z = chr(0)
        self.OWall1 = chr(219)
        self.OWall2 = chr(219)
        self.OWall3 = chr(219)
        self.CWall1 = chr(0)
        self.CWall2 = chr(0)
        self.CWall3 = chr(0)
        self.OSpell1 = chr(127)
        self.OSpell2 = chr(127)
        self.OSpell3 = chr(127)
        self.CSpell1 = chr(0)
        self.CSpell2 = chr(0)
        self.CSpell3 = chr(0)
        self.GBlock = chr(178)
        self.Rock = chr(79)
        self.EWall = chr(88)
        self.Trap5 = chr(0)
        self.TBlock = chr(0)
        self.TRock = chr(0)
        self.TGem = chr(0)
        self.TBlind = chr(0)
        self.TWhip = chr(0)
        self.TGold = chr(0)
        self.TTree = chr(0)
        self.Rope = chr(179)
        self.DropRope = chr(25)
        self.Amulet = chr(12)
        self.ShootRight = chr(26)
        self.ShootLeft = chr(27)
        self.Trap6 = chr(0)
        self.Trap7 = chr(0)
        self.Trap8 = chr(0)
        self.Trap9 = chr(0)
        self.Trap10 = chr(0)
        self.Trap11 = chr(0)
        self.Trap12 = chr(0)
        self.Trap13 = chr(0)
        self.Message = chr(5)

        self.LevelNumber = 1

        WINDOW_WIDTH = 640
        WINDOW_WIDTH = 640
